apiVersion: v1
kind: Service
metadata:
  name: parklense-vehicle-admin-backend-service
  labels:
    app: parklense-vehicle-admin-backend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: parklense-vehicle-admin-backend
