openapi: "3.0.1"
info:
  title: "Parklense Auth Service Dev API"
  version: "2025-07-15 07:59:54UTC"
servers:
- url: "https://api.parklensedev.com/{basePath}"
  variables:
    basePath:
      default: ""

paths:
  # Route all requests to the ALB (current Django app configuration)
  /{proxy+}:
    parameters:
    - name: "proxy+"
      in: "path"
      description: "Proxy path for all requests"
      required: true
      schema:
        type: "string"
    x-amazon-apigateway-any-method:
      responses:
        default:
          description: "Default response for ANY /{proxy+}"
      x-amazon-apigateway-integration:
        payloadFormatVersion: "1.0"
        type: "http_proxy"
        httpMethod: "ANY"
        uri: "http://parklense-auth-dev-alb-887676365.ap-south-1.elb.amazonaws.com/{proxy}"
        connectionType: "INTERNET"
        timeoutInMillis: 30000
        requestParameters:
          integration.request.path.proxy: "method.request.path.proxy"

x-amazon-apigateway-cors:
  allowMethods:
  - "GET"
  - "POST"
  - "PUT"
  - "DELETE"
  - "PATCH"
  - "OPTIONS"
  allowHeaders:
  - "Content-Type"
  - "X-Amz-Date"
  - "Authorization"
  - "X-Api-Key"
  - "X-Amz-Security-Token"
  - "X-Request-ID"
  - "X-Correlation-ID"
  exposeHeaders:
  - "X-Correlation-ID"
  - "X-Response-Time"
  - "X-API-Version"
  maxAge: 86400
  allowCredentials: false
  allowOrigins:
  - "*"

x-amazon-apigateway-importexport-version: "1.0" 