openapi: "3.0.1"
info:
  title: "Parklense API Gateway"
  description: "Unified API Gateway for Auth and Vehicle services"
  version: "1.0.0"
servers:
- url: "https://api.parklensedev.com"
paths:
  # Auth Service Routes

  /api/v1/auth:
    x-amazon-apigateway-any-method:
      responses:
        default:
          description: "Auth service base"
      x-amazon-apigateway-integration:
        requestParameters:
          overwrite:header.Host: "api.parklensedev.com"
        payloadFormatVersion: "1.0"
        type: "http_proxy"
        httpMethod: "ANY"
        uri: "arn:aws:elasticloadbalancing:ap-south-1:399600302704:listener/app/parklense-auth-internal-alb/7e8e589806dc02de/5badea5f98892f1c"
        connectionType: "VPC_LINK"
        connectionId: "fvhrmx"
        timeoutInMillis: 30000

  /api/v1/auth/{proxy+}:
    parameters:
    - name: "proxy+"
      in: "path"
      required: true
      schema:
        type: "string"
    x-amazon-apigateway-any-method:
      responses:
        default:
          description: "Auth service proxy"
      x-amazon-apigateway-integration:
        requestParameters:
          overwrite:header.Host: "api.parklensedev.com"
        payloadFormatVersion: "1.0"
        type: "http_proxy"
        httpMethod: "ANY"
        uri: "arn:aws:elasticloadbalancing:ap-south-1:399600302704:listener/app/parklense-auth-internal-alb/7e8e589806dc02de/5badea5f98892f1c"
        connectionType: "VPC_LINK"
        connectionId: "fvhrmx"
        timeoutInMillis: 30000

  /api/v1/profile:
    x-amazon-apigateway-any-method:
      responses:
        default:
          description: "Profile service base"
      x-amazon-apigateway-integration:
        requestParameters:
          overwrite:header.Host: "api.parklensedev.com"
        payloadFormatVersion: "1.0"
        type: "http_proxy"
        httpMethod: "ANY"
        uri: "arn:aws:elasticloadbalancing:ap-south-1:399600302704:listener/app/parklense-auth-internal-alb/7e8e589806dc02de/5badea5f98892f1c"
        connectionType: "VPC_LINK"
        connectionId: "fvhrmx"
        timeoutInMillis: 30000

  /api/v1/profile/{proxy+}:
    parameters:
    - name: "proxy+"
      in: "path"
      required: true
      schema:
        type: "string"
    x-amazon-apigateway-any-method:
      responses:
        default:
          description: "Profile service proxy"
      x-amazon-apigateway-integration:
        requestParameters:
          overwrite:header.Host: "api.parklensedev.com"
        payloadFormatVersion: "1.0"
        type: "http_proxy"
        httpMethod: "ANY"
        uri: "arn:aws:elasticloadbalancing:ap-south-1:399600302704:listener/app/parklense-auth-internal-alb/7e8e589806dc02de/5badea5f98892f1c"
        connectionType: "VPC_LINK"
        connectionId: "fvhrmx"
        timeoutInMillis: 30000

  # Vehicle Service Routes
  /api/v1/vehicles:
    x-amazon-apigateway-any-method:
      responses:
        default:
          description: "Vehicle service base"
      x-amazon-apigateway-integration:
        requestParameters:
          overwrite:header.Host: "api.parklensedev.com"
        payloadFormatVersion: "1.0"
        type: "http_proxy"
        httpMethod: "ANY"
        uri: "arn:aws:elasticloadbalancing:ap-south-1:399600302704:listener/app/parklense-vehicle-internal-alb/5b8f7853daebf0db/5378440b48953563"
        connectionType: "VPC_LINK"
        connectionId: "fvhrmx"
        timeoutInMillis: 30000

  /api/v1/vehicles/{proxy+}:
    parameters:
    - name: "proxy+"
      in: "path"
      required: true
      schema:
        type: "string"
    x-amazon-apigateway-any-method:
      responses:
        default:
          description: "Vehicle service proxy"
      x-amazon-apigateway-integration:
        requestParameters:
          overwrite:header.Host: "api.parklensedev.com"
        payloadFormatVersion: "1.0"
        type: "http_proxy"
        httpMethod: "ANY"
        uri: "arn:aws:elasticloadbalancing:ap-south-1:399600302704:listener/app/parklense-vehicle-internal-alb/5b8f7853daebf0db/5378440b48953563"
        connectionType: "VPC_LINK"
        connectionId: "fvhrmx"
        timeoutInMillis: 30000

  /api/v1/vehicle-types/{proxy+}:
    parameters:
    - name: "proxy+"
      in: "path"
      required: true
      schema:
        type: "string"
    x-amazon-apigateway-any-method:
      responses:
        default:
          description: "Vehicle types proxy"
      x-amazon-apigateway-integration:
        requestParameters:
          overwrite:header.Host: "api.parklensedev.com"
        payloadFormatVersion: "1.0"
        type: "http_proxy"
        httpMethod: "ANY"
        uri: "arn:aws:elasticloadbalancing:ap-south-1:399600302704:listener/app/parklense-vehicle-internal-alb/5b8f7853daebf0db/5378440b48953563"
        connectionType: "VPC_LINK"
        connectionId: "fvhrmx"
        timeoutInMillis: 30000

  /api/v1/users/initialize:
    x-amazon-apigateway-any-method:
      responses:
        default:
          description: "User initialization"
      x-amazon-apigateway-integration:
        requestParameters:
          overwrite:header.Host: "api.parklensedev.com"
        payloadFormatVersion: "1.0"
        type: "http_proxy"
        httpMethod: "ANY"
        uri: "arn:aws:elasticloadbalancing:ap-south-1:399600302704:listener/app/parklense-vehicle-internal-alb/5b8f7853daebf0db/5378440b48953563"
        connectionType: "VPC_LINK"
        connectionId: "fvhrmx"
        timeoutInMillis: 30000

  # Health Check Routes (Service-Specific)
  /health/auth:
    get:
      responses:
        default:
          description: "Auth service health check"
      x-amazon-apigateway-integration:
        requestParameters:
          overwrite:header.Host: "api.parklensedev.com"
        payloadFormatVersion: "1.0"
        type: "http_proxy"
        httpMethod: "GET"
        uri: "arn:aws:elasticloadbalancing:ap-south-1:399600302704:listener/app/parklense-auth-internal-alb/7e8e589806dc02de/5badea5f98892f1c"
        connectionType: "VPC_LINK"
        connectionId: "fvhrmx"
        timeoutInMillis: 30000

  /health/vehicles:
    get:
      responses:
        default:
          description: "Vehicle service health check"
      x-amazon-apigateway-integration:
        requestParameters:
          overwrite:header.Host: "api.parklensedev.com"
        payloadFormatVersion: "1.0"
        type: "http_proxy"
        httpMethod: "GET"
        uri: "arn:aws:elasticloadbalancing:ap-south-1:399600302704:listener/app/parklense-vehicle-internal-alb/5b8f7853daebf0db/5378440b48953563"
        connectionType: "VPC_LINK"
        connectionId: "fvhrmx"
        timeoutInMillis: 30000

  /health:
    get:
      responses:
        default:
          description: "Global health check (defaults to auth)"
      x-amazon-apigateway-integration:
        requestParameters:
          overwrite:header.Host: "api.parklensedev.com"
        payloadFormatVersion: "1.0"
        type: "http_proxy"
        httpMethod: "GET"
        uri: "arn:aws:elasticloadbalancing:ap-south-1:399600302704:listener/app/parklense-auth-internal-alb/7e8e589806dc02de/5badea5f98892f1c"
        connectionType: "VPC_LINK"
        connectionId: "fvhrmx"
        timeoutInMillis: 30000

  # Documentation Routes (Service-Specific)
  /docs/auth/schema:
    get:
      responses:
        default:
          description: "Auth service OpenAPI schema"
      x-amazon-apigateway-integration:
        requestParameters:
          overwrite:header.Host: "api.parklensedev.com"
        payloadFormatVersion: "1.0"
        type: "http_proxy"
        httpMethod: "GET"
        uri: "arn:aws:elasticloadbalancing:ap-south-1:399600302704:listener/app/parklense-auth-internal-alb/7e8e589806dc02de/5badea5f98892f1c"
        connectionType: "VPC_LINK"
        connectionId: "fvhrmx"
        timeoutInMillis: 30000

  /docs/vehicles/schema:
    get:
      responses:
        default:
          description: "Vehicle service OpenAPI schema"
      x-amazon-apigateway-integration:
        requestParameters:
          overwrite:header.Host: "api.parklensedev.com"
        payloadFormatVersion: "1.0"
        type: "http_proxy"
        httpMethod: "GET"
        uri: "arn:aws:elasticloadbalancing:ap-south-1:399600302704:listener/app/parklense-vehicle-internal-alb/5b8f7853daebf0db/5378440b48953563"
        connectionType: "VPC_LINK"
        connectionId: "fvhrmx"
        timeoutInMillis: 30000

  /docs/auth:
    get:
      responses:
        default:
          description: "Auth service Swagger UI"
      x-amazon-apigateway-integration:
        requestParameters:
          overwrite:header.Host: "api.parklensedev.com"
        payloadFormatVersion: "1.0"
        type: "http_proxy"
        httpMethod: "GET"
        uri: "arn:aws:elasticloadbalancing:ap-south-1:399600302704:listener/app/parklense-auth-internal-alb/7e8e589806dc02de/5badea5f98892f1c"
        connectionType: "VPC_LINK"
        connectionId: "fvhrmx"
        timeoutInMillis: 30000

  /docs/vehicles:
    get:
      responses:
        default:
          description: "Vehicle service Swagger UI"
      x-amazon-apigateway-integration:
        requestParameters:
          overwrite:header.Host: "api.parklensedev.com"
        payloadFormatVersion: "1.0"
        type: "http_proxy"
        httpMethod: "GET"
        uri: "arn:aws:elasticloadbalancing:ap-south-1:399600302704:listener/app/parklense-vehicle-internal-alb/5b8f7853daebf0db/5378440b48953563"
        connectionType: "VPC_LINK"
        connectionId: "fvhrmx"
        timeoutInMillis: 30000

  /docs/auth/redoc:
    get:
      responses:
        default:
          description: "Auth service ReDoc"
      x-amazon-apigateway-integration:
        requestParameters:
          overwrite:header.Host: "api.parklensedev.com"
        payloadFormatVersion: "1.0"
        type: "http_proxy"
        httpMethod: "GET"
        uri: "arn:aws:elasticloadbalancing:ap-south-1:399600302704:listener/app/parklense-auth-internal-alb/7e8e589806dc02de/5badea5f98892f1c"
        connectionType: "VPC_LINK"
        connectionId: "fvhrmx"
        timeoutInMillis: 30000

  /docs/vehicles/redoc:
    get:
      responses:
        default:
          description: "Vehicle service ReDoc"
      x-amazon-apigateway-integration:
        requestParameters:
          overwrite:header.Host: "api.parklensedev.com"
        payloadFormatVersion: "1.0"
        type: "http_proxy"
        httpMethod: "GET"
        uri: "arn:aws:elasticloadbalancing:ap-south-1:399600302704:listener/app/parklense-vehicle-internal-alb/5b8f7853daebf0db/5378440b48953563"
        connectionType: "VPC_LINK"
        connectionId: "fvhrmx"
        timeoutInMillis: 30000


x-amazon-apigateway-cors:
  allowMethods:
  - "DELETE"
  - "GET"
  - "OPTIONS"
  - "PATCH"
  - "POST"
  - "PUT"
  allowHeaders:
  - "authorization"
  - "content-type"
  - "x-api-key"
  - "x-app-version"
  - "x-device-id"
  - "x-platform"
  - "x-request-id"
  exposeHeaders:
  - "x-api-version"
  - "x-request-id"
  maxAge: 3600
  allowCredentials: false
  allowOrigins:
  - "https://api.parklensedev.com"
  - "https://admin.parklensedev.com"
  - "https://app.parklensedev.com"
  - "https://parklensedev.com"
  - "https://www.parklensedev.com"
  - "http://localhost:3000"
  - "http://localhost:3001"
  - "http://localhost:8080"

x-amazon-apigateway-importexport-version: "1.0"
