apiVersion: v1
kind: Service
metadata:
  name: parklense-auth-backend-service
  labels:
    app: parklense-auth-backend
    component: backend
spec:
  type: ClusterIP
  selector:
    app: parklense-auth-backend
    component: backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
  sessionAffinity: None 