apiVersion: apps/v1
kind: Deployment
metadata:
  name: parklense-auth-celery-worker
  labels:
    app: parklense-auth-celery-worker
    component: celery-worker
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: parklense-auth-celery-worker
      component: celery-worker
  template:
    metadata:
      labels:
        app: parklense-auth-celery-worker
        component: celery-worker
    spec:
      serviceAccountName: parklense-auth-sa
      terminationGracePeriodSeconds: 60
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      volumes:
        - name: parklense-auth-secrets-volume
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: parklense-auth-backend-secrets
        - name: logs-volume
          emptyDir: {}
      containers:
        - name: celery-worker
          image: ghcr.io/parklense-auth-service:latest
          imagePullPolicy: Always
          command:
            - celery
            - -A
            - config.celery
            - worker
            - -l
            - info
            - -Q
            - default,email,sms
            - --concurrency=4
            - --prefetch-multiplier=1
            - --max-tasks-per-child=1000
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "config.settings.production"
            - name: REDIS_URL
              value: "redis://redis-service:6379"
            - name: POSTGRES_HOST
              value: "postgres-service"
            - name: POSTGRES_PORT
              value: "5432"
            - name: CELERY_WORKER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: parklense-auth-secrets-volume
              mountPath: /mnt/secret-store
              readOnly: true
            - name: logs-volume
              mountPath: /app/logs
          lifecycle:
            postStart:
              exec:
                command: ["sh", "-c", "cp -R /mnt/secret-store/.env /app/.env"]
            preStop:
              exec:
                command: ["sh", "-c", "celery -A config.celery control shutdown"]
          livenessProbe:
            exec:
              command:
                - celery
                - -A
                - config.celery
                - inspect
                - ping
            initialDelaySeconds: 60
            timeoutSeconds: 30
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - celery
                - -A
                - config.celery
                - inspect
                - ping
            initialDelaySeconds: 30
            timeoutSeconds: 30
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000 