apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod-parklense-auth

resources:
  - ../../../base/auth
  - storage/pv.yaml
  - storage/pvc.yaml

# Environment-specific labels
labels:
  - pairs:
      environment: production
      tier: prod
    includeSelectors: false

# Patches for production environment
patches:
  # Backend Deployment patches
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: parklense-auth-backend
      spec:
        replicas: 3
        template:
          spec:
            serviceAccountName: prod-parklense-auth-sa
            containers:
            - name: parklense-auth-backend
              image: 399600302704.dkr.ecr.ap-south-1.amazonaws.com/parklense-auth-backend:latest
              resources:
                requests:
                  cpu: "2"
                  memory: "4Gi"
                limits:
                  cpu: "4"
                  memory: "8Gi"
              env:
              - name: WORKERS
                value: "4"
    target:
      kind: Deployment
      name: parklense-auth-backend

  # Celery Worker patches
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: parklense-auth-celery-worker
      spec:
        replicas: 3
        template:
          spec:
            serviceAccountName: prod-parklense-auth-sa
            containers:
            - name: celery-worker
              image: 399600302704.dkr.ecr.ap-south-1.amazonaws.com/parklense-auth-backend:latest
              resources:
                requests:
                  cpu: "1"
                  memory: "2Gi"
                limits:
                  cpu: "2"
                  memory: "4Gi"
              command:
                - celery
                - -A
                - config.celery
                - worker
                - -l
                - info
                - -Q
                - default,email,sms
                - --concurrency=4
                - --prefetch-multiplier=1
                - --max-tasks-per-child=1000
    target:
      kind: Deployment
      name: parklense-auth-celery-worker

  # Celery Beat patches
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: parklense-auth-celery-beat
      spec:
        replicas: 1
        template:
          spec:
            serviceAccountName: prod-parklense-auth-sa
            containers:
            - name: celery-beat
              image: 399600302704.dkr.ecr.ap-south-1.amazonaws.com/parklense-auth-backend:latest
              resources:
                requests:
                  cpu: "0.5"
                  memory: "1Gi"
                limits:
                  cpu: "1"
                  memory: "2Gi"
    target:
      kind: Deployment
      name: parklense-auth-celery-beat

  # Redis patches
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: parklense-auth-redis
      spec:
        replicas: 1
        template:
          spec:
            serviceAccountName: prod-parklense-auth-sa
            containers:
            - name: redis
              resources:
                requests:
                  cpu: "0.5"
                  memory: "1Gi"
                limits:
                  cpu: "1"
                  memory: "2Gi"
    target:
      kind: Deployment
      name: parklense-auth-redis

  # Ingress patches
  - patch: |-
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: parklense-auth-ingress
        annotations:
          alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:REGION:ACCOUNT:certificate/PROD_CERT_ID
          alb.ingress.kubernetes.io/cors-allow-origin: >-
            https://parklense.com,https://www.parklense.com,https://auth.parklense.com
          alb.ingress.kubernetes.io/load-balancer-attributes: deletion_protection.enabled=true
          alb.ingress.kubernetes.io/wafv2-acl-arn: arn:aws:wafv2:REGION:ACCOUNT:regional/webacl/parklense-auth-waf/WAF_ID
      spec:
        rules:
        - host: auth.parklense.com
          http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: parklense-auth-backend-service
                  port:
                    number: 80
        - host: auth-api.parklense.com
          http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: parklense-auth-backend-service
                  port:
                    number: 80
        tls:
          - hosts:
              - auth.parklense.com
              - auth-api.parklense.com
            secretName: parklense-auth-tls
    target:
      kind: Ingress
      name: parklense-auth-ingress

  # Secrets patches
  - patch: |-
      apiVersion: secrets-store.csi.x-k8s.io/v1
      kind: SecretProviderClass
      metadata:
        name: parklense-auth-backend-secrets
      spec:
        parameters:
          objects: |
            - objectName: arn:aws:secretsmanager:REGION:ACCOUNT:secret:parklense-auth-prod-secrets-SUFFIX
              objectAlias: ".env"
              objectType: "secretsmanager"
              objectVersionStage: "AWSCURRENT"
    target:
      kind: SecretProviderClass
      name: parklense-auth-backend-secrets

  # Service Account patches
  - patch: |-
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: parklense-auth-sa
        annotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT:role/parklense-auth-prod-role
    target:
      kind: ServiceAccount
      name: parklense-auth-sa

  # HPA patches - production scaling
  - patch: |-
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: parklense-auth-backend-hpa
      spec:
        minReplicas: 3
        maxReplicas: 15
        metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 60
        - type: Resource
          resource:
            name: memory
            target:
              type: Utilization
              averageUtilization: 70
    target:
      kind: HorizontalPodAutoscaler
      name: parklense-auth-backend-hpa

  - patch: |-
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: parklense-auth-celery-worker-hpa
      spec:
        minReplicas: 2
        maxReplicas: 10
        metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 50
        - type: Resource
          resource:
            name: memory
            target:
              type: Utilization
              averageUtilization: 60
    target:
      kind: HorizontalPodAutoscaler
      name: parklense-auth-celery-worker-hpa 