apiVersion: v1
kind: PersistentVolume
metadata:
  name: parklense-auth-prod-pv
  labels:
    environment: production
    app: parklense-auth-backend
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp3
  awsElasticBlockStore:
    volumeID: REPLACE_WITH_ACTUAL_PROD_VOLUME_ID
    fsType: ext4

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: parklense-auth-redis-prod-pv
  labels:
    environment: production
    app: parklense-auth-redis
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp3
  awsElasticBlockStore:
    volumeID: REPLACE_WITH_ACTUAL_PROD_REDIS_VOLUME_ID
    fsType: ext4

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: parklense-auth-beat-prod-pv
  labels:
    environment: production
    app: parklense-auth-celery-beat
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp3
  awsElasticBlockStore:
    volumeID: REPLACE_WITH_ACTUAL_PROD_BEAT_VOLUME_ID
    fsType: ext4 