apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: parklense-auth-pvc
  labels:
    environment: production
    app: parklense-auth-backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: gp3
  volumeName: parklense-auth-prod-pv

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: parklense-auth-redis-pvc
  labels:
    environment: production
    app: parklense-auth-redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: gp3
  volumeName: parklense-auth-redis-prod-pv

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: parklense-auth-beat-pvc
  labels:
    environment: production
    app: parklense-auth-celery-beat
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp3
  volumeName: parklense-auth-beat-prod-pv 