apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-parklense

resources:
  - ../../base
  - storage/pv.yaml
  - storage/pvc.yaml

# Environment-specific labels
labels:
  - pairs:
      environment: development
      tier: dev
    includeSelectors: false

# Patches for dev environment
patches:
  # Backend Deployment patches
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: parklense-auth-backend
      spec:
        replicas: 1
        template:
          spec:
            serviceAccountName: parklense-auth-secret-sa
            containers:
            - name: parklense-auth-backend
              image: 399600302704.dkr.ecr.ap-south-1.amazonaws.com/parklense-auth-service:Auth_setup___15___Refactor_URL-20250917-124129-f60f300
              resources: null  # Commented out for dev environment
              # resources:
              #   requests:
              #     cpu: "0.5"
              #     memory: "1Gi"
              #   limits:
              #     cpu: "1"
              #     memory: "2Gi"
              env:
              - name: WORKERS
                value: "2"
    target:
      kind: Deployment
      name: parklense-auth-backend

  # Celery Worker patches
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: parklense-auth-celery-worker
      spec:
        replicas: 1
        template:
          spec:
            serviceAccountName: parklense-auth-secret-sa
            containers:
            - name: parklense-auth-celery-worker
              image: 399600302704.dkr.ecr.ap-south-1.amazonaws.com/parklense-auth-service:Auth_setup___15___Refactor_URL-20250917-124129-f60f300
              resources: null  # Commented out for dev environment
              # resources:
              #   requests:
              #     cpu: "0.25"
              #     memory: "512Mi"
              #   limits:
              #     cpu: "0.5"
              #     memory: "1Gi"
              command:
                - celery
                - -A
                - config.celery
                - worker
                - -l
                - info
                - -Q
                - default,email,sms
                - --concurrency=2
                - --prefetch-multiplier=1
                - --max-tasks-per-child=1000
    target:
      kind: Deployment
      name: parklense-auth-celery-worker

  # Celery Beat patches
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: parklense-auth-celery-beat
      spec:
        replicas: 1
        template:
          spec:
            serviceAccountName: parklense-auth-secret-sa
            containers:
            - name: parklense-auth-celery-beat
              image: 399600302704.dkr.ecr.ap-south-1.amazonaws.com/parklense-auth-service:Auth_setup___15___Refactor_URL-20250917-124129-f60f300
              resources: null  # Commented out for dev environment
              # resources:
              #   requests:
              #     cpu: "0.1"
              #     memory: "256Mi"
              #   limits:
              #     cpu: "0.25"
              #     memory: "512Mi"
    target:
      kind: Deployment
      name: parklense-auth-celery-beat

  # Redis patches
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: parklense-auth-redis
      spec:
        replicas: 1
        template:
          spec:
            containers:
            - name: redis
              resources: null  # Commented out for dev environment
              # resources:
              #   requests:
              #     cpu: "0.1"
              #     memory: "256Mi"
              #   limits:
              #     cpu: "0.25"
              #     memory: "512Mi"
    target:
      kind: Deployment
      name: parklense-auth-redis

  # Ingress patches
  - patch: |-
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: parklense-auth-ingress
        annotations:
          alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:399600302704:certificate/6eb37406-7e5c-4612-9761-e49fcb1d3bf3
          alb.ingress.kubernetes.io/cors-allow-origin: >-
            https://parklensedev.com,https://*.parklensedev.com
          alb.ingress.kubernetes.io/load-balancer-name: parklense-auth-dev-alb
          alb.ingress.kubernetes.io/load-balancer-attributes: >-
            idle_timeout.timeout_seconds=60,deletion_protection.enabled=false
      spec:
        rules:
        - host: api.parklensedev.com
          http:
            paths:
            # Health check endpoint
            - path: /health
              pathType: Prefix
              backend:
                service:
                  name: parklense-auth-backend-service
                  port:
                    number: 80
            # Auth service endpoints (direct routes)
            - path: /auth
              pathType: Prefix
              backend:
                service:
                  name: parklense-auth-backend-service
                  port:
                    number: 80

            # API v1 endpoints (legacy routes)
            - path: /api/v1/auth
              pathType: Prefix
              backend:
                service:
                  name: parklense-auth-backend-service
                  port:
                    number: 80
            - path: /api/v1/profile
              pathType: Prefix
              backend:
                service:
                  name: parklense-auth-backend-service
                  port:
                    number: 80
            # Documentation endpoints
            - path: /api/schema
              pathType: Prefix
              backend:
                service:
                  name: parklense-auth-backend-service
                  port:
                    number: 80
            - path: /api/v1/swagger
              pathType: Prefix
              backend:
                service:
                  name: parklense-auth-backend-service
                  port:
                    number: 80
            - path: /api/v1/redoc
              pathType: Prefix
              backend:
                service:
                  name: parklense-auth-backend-service
                  port:
                    number: 80
            # Static files for documentation
            - path: /static
              pathType: Prefix
              backend:
                service:
                  name: parklense-auth-backend-service
                  port:
                    number: 80
            # Admin interface
            - path: /admin
              pathType: Prefix
              backend:
                service:
                  name: parklense-auth-backend-service
                  port:
                    number: 80
            # Root path - catch all remaining
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: parklense-auth-backend-service
                  port:
                    number: 80
        tls:
          - hosts:
              - api.parklensedev.com
            secretName: parklense-auth-tls
    target:
      kind: Ingress
      name: parklense-auth-ingress

  # Secrets patches
  - patch: |-
      apiVersion: secrets-store.csi.x-k8s.io/v1
      kind: SecretProviderClass
      metadata:
        name: parklense-auth-backend-secrets
      spec:
        parameters:
          objects: |
            - objectName: arn:aws:secretsmanager:ap-south-1:399600302704:secret:parklense-auth-service-dev-OQq1ud
              objectAlias: ".env"
              objectType: "secretsmanager"
    target:
      kind: SecretProviderClass
      name: parklense-auth-backend-secrets

  # HPA patches - reduce scaling for dev
  - patch: |-
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: parklense-auth-backend-autoscaler
      spec:
        minReplicas: 1
        maxReplicas: 2
    target:
      kind: HorizontalPodAutoscaler
      name: parklense-auth-backend-autoscaler

  - patch: |-
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: parklense-auth-celery-worker-autoscaler
      spec:
        minReplicas: 1
        maxReplicas: 2
    target:
      kind: HorizontalPodAutoscaler
      name: parklense-auth-celery-worker-autoscaler 
