apiVersion: apps/v1
kind: Deployment
metadata:
  name: parklense-auth-celery-worker
  labels:
    app: parklense-auth-celery-worker
    component: celery-worker
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: parklense-auth-celery-worker
      component: celery-worker
  template:
    metadata:
      labels:
        app: parklense-auth-celery-worker
        component: celery-worker
    spec:
      serviceAccountName: parklense-auth-secret-sa
      terminationGracePeriodSeconds: 30
      # securityContext:
      #   runAsNonRoot: true
      #   runAsUser: 1000
      #   runAsGroup: 1000
      #   fsGroup: 1000
      volumes:
        - name: parklense-auth-secrets-volume
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: parklense-auth-backend-secrets
        - name: parklense-auth-storage
          emptyDir: {}
        - name: logs-volume
          emptyDir: {}
          # Removed hosts-volume
      containers:
        - name: parklense-auth-celery-worker
          image: 399600302704.dkr.ecr.ap-south-1.amazonaws.com/parklense-auth-service:Update_Dockerfile_to_set_produ-20250719-062143-8fcc7bb
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "config.settings.production"
            - name: REDIS_URL
              value: "redis://redis-service:6379/0"
            - name: CELERY_BROKER_URL
              value: "redis://redis-service:6379/0"
            - name: CELERY_WORKER_CONCURRENCY
              value: "4"
            - name: CELERY_WORKER_MAX_TASKS_PER_CHILD
              value: "25"
            - name: CELERY_WORKER_PREFETCH_MULTIPLIER
              value: "1"
            - name: DJANGO_REDIS_PARSER_CLASS
              value: "redis.connection.DefaultParser"
            - name: LOG_LEVEL
              value: "DEBUG"
            - name: DJANGO_LOG_LEVEL
              value: "DEBUG"
            - name: CELERY_LOG_LEVEL
              value: "DEBUG"
          envFrom:
            - configMapRef:
                name: parklense-env-config
          command:
            - celery
            - -A
            - config.celery
            - worker
            - -l
            - debug
            - -Q
            - default,email,sms
            - --concurrency=4
            - --prefetch-multiplier=1
          volumeMounts:
            - name: parklense-auth-secrets-volume
              mountPath: /mnt/secret-store
              readOnly: true
            - name: parklense-auth-storage
              mountPath: /app/media
            - name: logs-volume
              mountPath: /app/logs
              # Removed hosts-volume mount
          lifecycle:
            postStart:
              exec:
                command: ['sh', '-c', 'cp -R /mnt/secret-store/.env /app/.env']
          # securityContext:
          #   allowPrivilegeEscalation: false
          #   readOnlyRootFilesystem: false
          #   capabilities:
          #     drop:
          #       - ALL
          #   runAsNonRoot: true
          #   runAsUser: 1000
          #   runAsGroup: 1000
