apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: parklense-auth-pvc
  labels:
    environment: development
    app: parklense-auth-backend
    storage-type: efs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: efs-sc
  volumeName: parklense-auth-dev-pv