apiVersion: apps/v1
kind: Deployment
metadata:
  name: parklens-frontend
  labels:
    app: parklens-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parklens-frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: parklens-frontend
    spec:
      volumes:
        - name: nginx-configuration
          configMap:
            name: frontend-nginx-config
      containers:
        - name: parklens-frontend
          image: "placeholder.ecr.repository/parklens-frontend:latest"  # Replace with actual image
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "500m"
              memory: "500Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          ports:
            - containerPort: 80
          volumeMounts:  
            - name: nginx-configuration
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 80
          #   initialDelaySeconds: 30
          #   periodSeconds: 30
          #   timeoutSeconds: 10
          #   failureThreshold: 3
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 80
          #   initialDelaySeconds: 10
          #   periodSeconds: 10
          #   timeoutSeconds: 5
          #   failureThreshold: 3
          # startupProbe:
          #   httpGet:
          #     path: /health
          #     port: 80
          #   failureThreshold: 30
          #   periodSeconds: 10
          #   timeoutSeconds: 5 
