apiVersion: v1
kind: PersistentVolume
metadata:
  name: vehicle-media-dev-pv
  labels:
    environment: development
    app: parklense-vehicle-backend
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp3
  awsElasticBlockStore:
    volumeID: REPLACE_WITH_ACTUAL_VEHICLE_MEDIA_VOLUME_ID
    fsType: ext4

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vehicle-static-dev-pv
  labels:
    environment: development
    app: parklense-vehicle-backend
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp3
  awsElasticBlockStore:
    volumeID: REPLACE_WITH_ACTUAL_VEHICLE_STATIC_VOLUME_ID
    fsType: ext4 