apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vehicle-media-pvc
  namespace: dev-parklense-vehicle
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vehicle-static-pvc
  namespace: dev-parklense-vehicle
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2 