name: Auth Service - Deploy to Development

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Auth service Docker image to deploy'
        required: true
      sha:
        description: 'Git SHA of the commit'
        required: true
      commit_message:
        description: 'Original commit message'
        required: true

jobs:
  deploy-auth-dev:
    runs-on: ubuntu-latest
    environment: 
      name: development
      url: https://auth.parklensedev.com
    
    steps:
      - name: Display Deployment Information
        run: |
          echo "Auth Image: ${{ github.event.inputs.image }}"
          echo "SHA: ${{ github.event.inputs.sha }}"
          echo "Commit Message: ${{ github.event.inputs.commit_message }}"

      - name: Checkout deployment repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0

      - name: Set environment variables
        run: |
          echo "AUTH_IMAGE=${{ github.event.inputs.image }}" >> $GITHUB_ENV
          echo "COMMIT_SHA=${{ github.event.inputs.sha }}" >> $GITHUB_ENV
          echo "COMMIT_MESSAGE=${{ github.event.inputs.commit_message }}" >> $GITHUB_ENV
          echo "DEPLOY_ACTOR=${{ github.actor }}" >> $GITHUB_ENV

      - name: Update auth service image tags
        run: |
          # Update auth service image tags in overlay files
          sed -i 's|image: .*|image: '"$AUTH_IMAGE"'|' k8s/backend/overlays/auth/dev/kustomization.yaml

      - name: Commit and push changes
        run: |
          git config --local user.email "deployment@parklense.com"
          git config --local user.name "Parklense Auth Deployment Bot"
          
          if git diff --quiet; then
            echo "No changes to commit"
          else
            git add k8s/backend/overlays/auth/dev/
            git commit -m "🚀 Auth Service Deploy to dev: ${{ env.COMMIT_MESSAGE }} (SHA: ${{ env.COMMIT_SHA }})"
            git push origin main
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update Kubernetes configuration
        run: |
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

      - name: Deploy auth service to development environment
        run: |
          kubectl apply -k k8s/backend/overlays/auth/dev
          kubectl rollout status deployment/parklense-auth-backend -n dev-parklense --timeout=300s
          kubectl rollout status deployment/parklense-auth-celery-worker -n dev-parklense --timeout=300s
          kubectl rollout status deployment/parklense-auth-celery-beat -n dev-parklense --timeout=300s

      - name: Verify auth deployment
        run: |
          kubectl get pods -n dev-parklense -l app=parklense-auth-backend
          kubectl get services -n dev-parklense -l app=parklense-auth-backend
          kubectl get ingress -n dev-parklense

      - name: Run auth health checks
        run: |
          echo "Waiting for auth deployment to be ready..."
          sleep 30
          
          # Test auth service health endpoint
          curl -f -s -o /dev/null https://auth.parklensedev.com/api/health/ || echo "Auth health check failed, but continuing..."

      - name: Send deployment success notification
        if: success()
        uses: 8398a7/action-slack@v3
        with:
          status: success
          channel: parklens-deployment-alerts
          text: |
            :rocket: *Auth Service - Dev Deployed Successfully*
            *By:* ${{ env.DEPLOY_ACTOR }} | *SHA:* ${{ env.COMMIT_SHA }}
            *URL:* https://api.parklensedev.com
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Send deployment failure notification
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          channel: parklens-deployment-alerts
          text: |
            :x: *Auth Service - Dev Deployment Failed*
            *By:* ${{ env.DEPLOY_ACTOR }} | *SHA:* ${{ env.COMMIT_SHA }}
            Check logs for details.
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} 